package com.abbas.ecommerce.common.exception;

import lombok.Getter;

@Getter
public enum ErrorMessageType {
    //IDENTİTY-SERVİCE HATA MESAJ TİPLERİ
    GENERAL_EXCEPTION_IDENTITY(1001,"IDENTITY-SERVİCE GENEL HATA"),
    USERNAME_ALREADY_EXIST(1002,"KULLANICI ÇOKTAN KAYITLI"),
    EMAIL_ALREADY_EXIST(1003,"EMAİL ÇOKTAN KAYITLI"),
    USER_NOT_FOUND(1004,"KULLANICI BULUNAMADI"),
    USER_OR_PASSWORD_INCORECT(1005,"KULLANICI ADI VEYA ŞİFRE HATALI"),
    TOKEN_IS_NOT_VALID(1006,"GEÇERSİZ TOKEN"),
    TOKEN_EXPIRED(1007,"TOKEN GEÇERLİLİK SÜRESİ BİTMİŞTİR"),
    TOKEN_BLACKLIST(1008,"TOKEN BLACKLİSTTE"),

    //PRODUCT-SERVİCE HATA MESAJ TİPLERİ
    GENERAL_EXCEPTION_PRODUCT(2001,"PRODUCT-SERVİCE GENEL HATA"),
    PRODUCT_NOT_FOUND(2002,"ÜRÜN BULUNAMADI"),

    ORDER_NOT_FOUND(3001,"SİPARİŞ BULUNAMADI"),

    ORDER_BASKET_NOT_FOUND_BY_USERID(3010,"USERID YE AİT SEPET BULUNAMADI"),


    GENERAL_VALIDATION_INCORRECT(9001,"GENEL VALİDASYON HATASI");

    private Integer code;

    private String desc;

    ErrorMessageType(Integer code, String desc) {
        this.code = code;
        this.desc = desc;
    }
}
